language: node_js
node_js:
  - "node"
  - "lts/*"

cache:
  directories:
    - node_modules

before_install:
  - docker run grokzen/redis-cluster:lastest

install:
  - npm install

services:
  - docker
  - redis-server

